networks:
  store:
    name: store


services:
  mysql:
    image: mysql-storedb:latest
    container_name: store_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: store
      MYSQL_USER: store
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  
    networks:
      - store
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M 

  php:
    image: php-lifestylestore:latest 
    container_name: store
    ports:
      - "8080:80"
    networks:
      - store
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 64M   