networks:
  store:


services:
  mysql:
    image: mysql-storedb:latest
    container_name: store_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: store
      MYSQL_USER: store
      MYSQL_PASSWORD: password
    networks:
      - store

  php:
    image: php-lifestylestore:latest 
    container_name: store
    ports:
      - "8080:80"
    networks:
      - store